name: publish

on:
  release:
    types:
      - published

jobs:
  publish:
    name: publish to npm
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@master

      - name: install Node.js
        uses: actions/setup-node@master

      - name: install dependencies
        run: npm ci

      - name: publish
        run: npm publish
        with:
          registry-url: https://registry.npmjs.org/
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
