name: tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  run-tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@master

      - name: install Node.js
        uses: actions/setup-node@master

      - name: install dependencies
        run: npm ci

      - name: test
        run: npm test
